AWSTemplateFormatVersion: "2010-09-09"
Description: Creates Auto Scaling Groups for Web Servers
Parameters:
  VPCStackName:
    Description: Name of the stack that contains the VPC resources
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: WebVPC
  SGStackName:
    Description: Name of the stack that contains the Security Group resources
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: WebSG
  ALBStackName:
    Description: Name of the stack that contains the Application Load Balancing resources
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: WebALB
  WebServerKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the Web Server instance
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: AWS20171012Coda
    ConstraintDescription: Must be the name of an existing EC2 KeyPair
Resources:
  WebServerLC:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      ImageId: ami-4fa0c235
      IamInstanceProfile: S3-Admin-Access
      KeyName: !Ref WebServerKeyName
      EbsOptimized: false
      UserData:
        Fn::Base64:
          !Join
            - ""
            - - "#!/bin/bash\n"
              - "aws s3 sync --delete s3://eyamrog-wordpressmedia/ /var/www/html/wp-content/uploads/\n"
              - "aws s3 sync --delete s3://eyamrog-wordpresscode/ /var/www/html/\n"
      InstanceType: t2.micro
      InstanceMonitoring: false
      SecurityGroups:
        - Fn::ImportValue:
            !Sub "${SGStackName}-WebSG"
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
      AssociatePublicIpAddress: true
Outputs:
  WebServerLC:
    Description: Web Server Launch Configuration
    Value: !Ref WebServerLC
    Export:
      Name: !Sub "${AWS::StackName}-WebServerLC"
