AWSTemplateFormatVersion: "2010-09-09"
Description: Creates Auto Scaling Groups for Web Servers
Parameters:
  VPCStackName:
    Description: Name of the stack that contains the VPC resources
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: WebVPC
  SGStackName:
    Description: Name of the stack that contains the Security Group resources
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: WebSG
  ALBStackName:
    Description: Name of the stack that contains the Application Load Balancing resources
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: WebALB
  WebServerKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the Web Server instance
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: AWS20171012Coda
    ConstraintDescription: Must be the name of an existing EC2 KeyPair
Resources:
  WebServerRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: S3-Admin-Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: S3AdminAccess
                Effect: Allow
                Action: s3:*
                Resource: "*"
  WebServerInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: /
      Roles:
        - !Ref WebServerRole
  WebServerLC:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      ImageId: ami-4fa0c235
      IamInstanceProfile: !Ref WebServerInstanceProfile
      KeyName: !Ref WebServerKeyName
      EbsOptimized: false
      UserData:
        Fn::Base64:
          !Join
            - ""
            - - "#!/bin/bash\n"
              - "aws s3 sync --delete s3://eyamrog-wordpressmedia/ /var/www/html/wp-content/uploads/\n"
              - "aws s3 sync --delete s3://eyamrog-wordpresscode/ /var/www/html/\n"
      InstanceType: t2.micro
      InstanceMonitoring: false
      SecurityGroups:
        - Fn::ImportValue:
            !Sub "${SGStackName}-WebSG"
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
      AssociatePublicIpAddress: true
  WebServerASG:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      Tags:
        - Key: Name
          Value: WebServerASG
          PropagateAtLaunch: yes
      LaunchConfigurationName: !Ref WebServerLC
      TargetGroupARNs:
        - Fn::ImportValue:
            !Sub "${ALBStackName}-WebServerTG1"
      VPCZoneIdentifier:
        - Fn::ImportValue:
            !Sub "${VPCStackName}-PublicSubnetA"
        - Fn::ImportValue:
            !Sub "${VPCStackName}-PublicSubnetB"
        - Fn::ImportValue:
            !Sub "${VPCStackName}-PublicSubnetC"
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      DesiredCapacity: 0
      MinSize: 0
      MaxSize: 1
      Cooldown: 60
  WebServerReadLC:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      ImageId: ami-5babc921
      IamInstanceProfile: !Ref WebServerInstanceProfile
      KeyName: !Ref WebServerKeyName
      EbsOptimized: false
      UserData:
        Fn::Base64:
          !Join
            - ""
            - - "#!/bin/bash\n"
              - "aws s3 sync --delete s3://eyamrog-wordpressmedia/ /var/www/html/wp-content/uploads/\n"
              - "aws s3 sync --delete s3://eyamrog-wordpresscode/ /var/www/html/\n"
      InstanceType: t2.micro
      InstanceMonitoring: false
      SecurityGroups:
        - Fn::ImportValue:
            !Sub "${SGStackName}-WebSG"
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
      AssociatePublicIpAddress: true
  WebServerReadASG:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      Tags:
        - Key: Name
          Value: WebServerReadASG
          PropagateAtLaunch: yes
      LaunchConfigurationName: !Ref WebServerReadLC
      TargetGroupARNs:
        - Fn::ImportValue:
            !Sub "${ALBStackName}-WebServerReadTG1"
      VPCZoneIdentifier:
        - Fn::ImportValue:
            !Sub "${VPCStackName}-PublicSubnetA"
        - Fn::ImportValue:
            !Sub "${VPCStackName}-PublicSubnetB"
        - Fn::ImportValue:
            !Sub "${VPCStackName}-PublicSubnetC"
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      DesiredCapacity: 0
      MinSize: 0
      MaxSize: 8
      Cooldown: 60
      NotificationConfigurations:
        - TopicARN:
            !Ref WebServerReadNotifications
          NotificationTypes:
            - autoscaling:EC2_INSTANCE_LAUNCH
            - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
            - autoscaling:EC2_INSTANCE_TERMINATE
            - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
  WebServerReadScaleOutPolicy:
    Type: "AWS::AutoScaling::ScalingPolicy"
    Properties:
      AutoScalingGroupName:
        !Ref WebServerReadASG
      PolicyType: StepScaling
      AdjustmentType: ChangeInCapacity
      StepAdjustments:
        - MetricIntervalLowerBound: 0
          MetricIntervalUpperBound: ""
          ScalingAdjustment: 2
      EstimatedInstanceWarmup: 60
  WebServerReadScaleInPolicy:
    Type: "AWS::AutoScaling::ScalingPolicy"
    Properties:
      AutoScalingGroupName:
        !Ref WebServerReadASG
      PolicyType: StepScaling
      AdjustmentType: ChangeInCapacity
      StepAdjustments:
        - MetricIntervalLowerBound: ""
          MetricIntervalUpperBound: 0
          ScalingAdjustment: -1
      EstimatedInstanceWarmup: 60
  WebServerReadCPUUtilizationHighAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: WebServerReadCPUUtilizationHighAlarm
      AlarmDescription: Breach threshold of 75% of High CPUUtilization
      MetricName: CPUUtilization
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 75
      EvaluationPeriods: 1
      AlarmActions:
        - !Ref WebServerReadScaleOutPolicy
        - !Ref WebServerReadScaleOutNotifications
      Namespace: AWS/EC2
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            !Ref WebServerReadASG
      Statistic: Average
      Period: 300
      TreatMissingData: missing
  WebServerReadCPUUtilizationLowAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: WebServerReadCPUUtilizationLowAlarm
      AlarmDescription: Breach threshold of 25% of Low CPUUtilization
      MetricName: CPUUtilization
      ComparisonOperator: LessThanOrEqualToThreshold
      Threshold: 25
      EvaluationPeriods: 1
      AlarmActions:
        - !Ref WebServerReadScaleInPolicy
        - !Ref WebServerReadScaleInNotifications
      Namespace: AWS/EC2
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            !Ref WebServerReadASG
      Statistic: Average
      Period: 300
      TreatMissingData: missing
  WebServerReadNotifications:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: WebServerReadNotifications
      DisplayName: WebServerReadNotifications
  WebServerReadNotificationsSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint: xyz@example.com
      Protocol: email
      TopicArn: !Ref WebServerReadNotifications
  WebServerReadScaleOutNotifications:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: WebServerReadScaleOutNotifications
      DisplayName: WebServerReadScaleOutNotifications
  WebServerReadScaleOutNotificationsSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint: xyz@example.com
      Protocol: email
      TopicArn: !Ref WebServerReadScaleOutNotifications
  WebServerReadScaleInNotifications:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: WebServerReadScaleInNotifications
      DisplayName: WebServerReadScaleInNotifications
  WebServerReadScaleInNotificationsSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint: xyz@example.com
      Protocol: email
      TopicArn: !Ref WebServerReadScaleInNotifications
Outputs:
  WebServerLC:
    Description: Web Server Launch Configuration
    Value: !Ref WebServerLC
    Export:
      Name: !Sub "${AWS::StackName}-WebServerLC"
  WebServerASG:
    Description: Web Server Auto Scaling Group
    Value: !Ref WebServerASG
    Export:
      Name: !Sub "${AWS::StackName}-WebServerASG"
  WebServerReadLC:
    Description: Web Server Launch Configuration
    Value: !Ref WebServerReadLC
    Export:
      Name: !Sub "${AWS::StackName}-WebServerReadLC"
  WebServerReadASG:
    Description: Web Server Auto Scaling Group for Read Users
    Value: !Ref WebServerReadASG
    Export:
      Name: !Sub "${AWS::StackName}-WebServerReadASG"
  WebServerReadScaleOutPolicy:
    Description: Web Server Auto Scaling Scale Out Policy for Read Users
    Value: !Ref WebServerReadScaleOutPolicy
    Export:
      Name: !Sub "${AWS::StackName}-WebServerReadScaleOutPolicy"
  WebServerReadScaleInPolicy:
    Description: Web Server Auto Scaling Scale In Policy for Read Users
    Value: !Ref WebServerReadScaleInPolicy
    Export:
      Name: !Sub "${AWS::StackName}-WebServerReadScaleInPolicy"
  WebServerReadCPUUtilizationHighAlarmName:
    Description: WebServerReadCPUUtilizationHighAlarmName alarm name
    Value: !Ref WebServerReadCPUUtilizationHighAlarm
    Export:
      Name: !Sub "${AWS::StackName}-WebServerReadCPUUtilizationHighAlarmName"
  WebServerReadCPUUtilizationHighAlarmArn:
    Description: WebServerReadCPUUtilizationHighAlarmArn alarm ARN
    Value:
      !GetAtt
        - WebServerReadCPUUtilizationHighAlarm
        - Arn
    Export:
      Name: !Sub "${AWS::StackName}-WebServerReadCPUUtilizationHighAlarmArn"
  WebServerReadCPUUtilizationLowAlarmName:
    Description: WebServerReadCPUUtilizationLowAlarmName alarm name
    Value: !Ref WebServerReadCPUUtilizationLowAlarm
    Export:
      Name: !Sub "${AWS::StackName}-WebServerReadCPUUtilizationLowAlarmName"
  WebServerReadCPUUtilizationLowAlarmArn:
    Description: WebServerReadCPUUtilizationLowAlarmArn alarm ARN
    Value:
      !GetAtt
        - WebServerReadCPUUtilizationLowAlarm
        - Arn
    Export:
      Name: !Sub "${AWS::StackName}-WebServerReadCPUUtilizationLowAlarmArn"
  WebServerReadNotificationsArn:
    Description: WebServerReadNotifications topic ARN
    Value: !Ref WebServerReadNotifications
    Export:
      Name: !Sub "${AWS::StackName}-WebServerReadNotificationsArn"
  WebServerReadNotificationsName:
    Description: WebServerReadNotifications topic name
    Value:
      !GetAtt
        - WebServerReadNotifications
        - TopicName
    Export:
      Name: !Sub "${AWS::StackName}-WebServerReadNotificationsName"
  WebServerReadScaleOutNotificationsArn:
    Description: WebServerReadScaleOutNotifications topic ARN
    Value: !Ref WebServerReadScaleOutNotifications
    Export:
      Name: !Sub "${AWS::StackName}-WebServerReadScaleOutNotificationsArn"
  WebServerReadScaleOutNotificationsName:
    Description: WebServerReadScaleOutNotifications topic name
    Value:
      !GetAtt
        - WebServerReadScaleOutNotifications
        - TopicName
    Export:
      Name: !Sub "${AWS::StackName}-WebServerReadScaleOutNotificationsName"
  WebServerReadScaleInNotificationsArn:
    Description: WebServerReadScaleInNotifications topic ARN
    Value: !Ref WebServerReadScaleInNotifications
    Export:
      Name: !Sub "${AWS::StackName}-WebServerReadScaleInNotificationsArn"
  WebServerReadScaleInNotificationsName:
    Description: WebServerReadScaleInNotifications topic name
    Value:
      !GetAtt
        - WebServerReadScaleInNotifications
        - TopicName
    Export:
      Name: !Sub "${AWS::StackName}-WebServerReadScaleInNotificationsName"
