AWSTemplateFormatVersion: "2010-09-09"
Description: Creates Application Load Balancers for Web Servers
Parameters:
  VPCStackName:
    Description: Name of the stack that contains the VPC resources
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: WebVPC
  SGStackName:
    Description: Name of the stack that contains the Security Group resources
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: WebSG
Resources:
  WebServerALB:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: WebServerALB
      Tags:
      - Key: Name
        Value: WebServerALB
      Type: application
      IpAddressType: ipv4
      Scheme: internet-facing
      Subnets:
      - Fn::ImportValue:
          !Sub "${VPCStackName}-PublicSubnetA"
      - Fn::ImportValue:
          !Sub "${VPCStackName}-PublicSubnetB"
      SecurityGroups:
      - Fn::ImportValue:
          !Sub "${SGStackName}-WebSG"
Outputs:
  WebServerALB:
    Description: Web Server Application Load Balancer
    Value: !Ref WebServerALB
    Export:
      Name: !Sub "${AWS::StackName}-WebServerALB"