AWSTemplateFormatVersion: "2010-09-09"
Description: Creates Application Load Balancers for Web Servers
Parameters:
  VPCStackName:
    Description: Name of the stack that contains the VPC resources
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: WebVPC
  SGStackName:
    Description: Name of the stack that contains the Security Group resources
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: WebSG
Resources:
  WebServerALB:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: WebServerALB
      Tags:
        - Key: Name
          Value: WebServerALB
      Type: application
      IpAddressType: ipv4
      Scheme: internet-facing
      Subnets:
        - Fn::ImportValue:
            !Sub "${VPCStackName}-PublicSubnetA"
        - Fn::ImportValue:
            !Sub "${VPCStackName}-PublicSubnetB"
        - Fn::ImportValue:
            !Sub "${VPCStackName}-PublicSubnetC"
      SecurityGroups:
        - Fn::ImportValue:
            !Sub "${SGStackName}-WebSG"
  WebServerTG1:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Name: WebServerTG1
      Tags:
        - Key: Name
          Value: WebServerTG1
      Protocol: HTTP
      Port: 80
      TargetType: instance
      HealthCheckProtocol: HTTP
      HealthCheckPath: /albhealthcheck.html
      HealthCheckPort: traffic-port
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckTimeoutSeconds: 5
      HealthCheckIntervalSeconds: 10
      Matcher:
        HttpCode: 200
      VpcId:
        Fn::ImportValue:
          !Sub "${VPCStackName}-VirtualPrivateCloud"
  WebServerListener1:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      Protocol: HTTP
      Port: 80
      LoadBalancerArn: !Ref WebServerALB
      DefaultActions:
        - TargetGroupArn: !Ref WebServerTG1
          Type: forward
  WebServerReadALB:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: WebServerReadALB
      Tags:
        - Key: Name
          Value: WebServerReadALB
      Type: application
      IpAddressType: ipv4
      Scheme: internet-facing
      Subnets:
        - Fn::ImportValue:
            !Sub "${VPCStackName}-PublicSubnetA"
        - Fn::ImportValue:
            !Sub "${VPCStackName}-PublicSubnetB"
        - Fn::ImportValue:
            !Sub "${VPCStackName}-PublicSubnetC"
      SecurityGroups:
        - Fn::ImportValue:
            !Sub "${SGStackName}-WebSG"
  WebServerReadTG1:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Name: WebServerReadTG1
      Tags:
        - Key: Name
          Value: WebServerReadTG1
      Protocol: HTTP
      Port: 80
      TargetType: instance
      HealthCheckProtocol: HTTP
      HealthCheckPath: /albhealthcheck.html
      HealthCheckPort: traffic-port
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckTimeoutSeconds: 5
      HealthCheckIntervalSeconds: 10
      Matcher:
        HttpCode: 200
      VpcId:
        Fn::ImportValue:
          !Sub "${VPCStackName}-VirtualPrivateCloud"
  WebServerReadListener1:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      Protocol: HTTP
      Port: 80
      LoadBalancerArn: !Ref WebServerReadALB
      DefaultActions:
        - TargetGroupArn: !Ref WebServerReadTG1
          Type: forward
Outputs:
  WebServerALB:
    Description: Web Server Application Load Balancer
    Value: !Ref WebServerALB
    Export:
      Name: !Sub "${AWS::StackName}-WebServerALB"
  WebServerTG1:
    Description: Web Server ALB Target Group 1
    Value: !Ref WebServerTG1
    Export:
      Name: !Sub "${AWS::StackName}-WebServerTG1"
  WebServerListener1:
    Description: Web Server Listener 1
    Value: !Ref WebServerListener1
    Export:
      Name: !Sub "${AWS::StackName}-WebServerListener1"
  WebServerReadALB:
    Description: Web Server Application Load Balancer for Read Users
    Value: !Ref WebServerReadALB
    Export:
      Name: !Sub "${AWS::StackName}-WebServerReadALB"
  WebServerReadTG1:
    Description: Web Server ALB Target Group 1 for Read Users
    Value: !Ref WebServerReadTG1
    Export:
      Name: !Sub "${AWS::StackName}-WebServerReadTG1"
  WebServerReadListener1:
    Description: Web Server Listener 1 for Read Users
    Value: !Ref WebServerReadListener1
    Export:
      Name: !Sub "${AWS::StackName}-WebServerReadListener1"
