AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a Lambda Function to determine the latest Amazon Linux AMI in the Region and in the required AMI Architecture
Parameters:
  AMIArchitecture:
    Description: Name of the required AMI Architecture
    Type: String
    AllowedValues:
      - PV64
      - HVM64
      - HVMG2
    Default: HVM64
  LambdaCodeS3BucketName:
    Description: Name of the existing S3 Bucket where Lambda Function Code is stored
    Type: String
    AllowedPattern: ^[-.a-z0-9]*$
    Default: eyamrog-wordpress
    ConstraintDescription: Bucket names can contain lowercase letters, numbers, hyphens and periods (.)
Resources:
  AMIInfo:
    Type: "Custom::AMIInfo"
    Properties:
      ServiceToken:
        !GetAtt
          - AMIInfoFunction
          - Arn
      Region: !Ref "AWS::Region"
      Architecture: !Ref AMIArchitecture
  AMIInfoFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !Ref LambdaCodeS3BucketName
        S3Key: amilookup.zip
      Handler:
        !Join
          - ""
          - - "amilookup"
            - ".handler"
      Role:
        !GetAtt
          - AMIInfoFunctionExecutionRole
          - Arn
      Runtime: nodejs6.10
      Timeout: 30
  AMIInfoFunctionExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AMIInfoFunctionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AMIInfoFunctionLogs
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
              - Sid: AMIInfoFunctionDescribeImages
                Effect: Allow
                Action:
                  - ec2:DescribeImages
                Resource: "*"
Outputs:
  AMIID:
    Description: The latest Amazon Linux AMI ID
    Value:
      !GetAtt
        - AMIInfo
        - Id
    Export:
      Name: !Sub "${AWS::StackName}-AMIID"
